name: event_booking
version: 1.0.0+2
publish_to: none
description: Event Booking
environment: 
  sdk: '>=2.19.6 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  flutter: 
    sdk: flutter
  flutter_native_splash: ^2.2.19
  flutter_launcher_icons: ^0.13.1
  google_fonts: ^4.0.4
  flutter_svg: ^2.0.5
  pinput: ^2.2.31
  avatar_stack: ^1.2.0

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
   - assets/
   - assets/logo.png
   - assets/splash_logo.png


flutter_native_splash:
  color: "#ffffff"
  image: assets/splash_logo.png

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/logo.png"
  remove_alpha_ios: true


 
